/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package every.name.counts;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;

public class MatcherTest {

    @Test
    public void matchFeatures(){
        List<String> features = Arrays.asList("Celesnik","41014","Sch","RudolJ","1.8505","alkwalger","Ass ing","6. Des. 1942 hatas","-decies","20.Feb. 1943","0.2 rk.Jugoslawe","L.R.O.","Jterbeuvlunde Jterbeuwl hunde");

        Prisoner prisoner = new Matcher().match(features);

        assert prisoner.getLastName().equals("Celesnik");
        assert prisoner.getPrisonerNumber().equals("41014");
        assert prisoner.getCategory().equals("Sch");
    }
}
