/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package every.name.counts;

public class App {

    public static void main(String[] args) {
        new TextExtractor().extractText();
    }
}
