
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: git clone git@github.com:LorenzoCianciaruso/every-name-counts.git

    - name: Build step
      run: ./gradlew build
